sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=db72eba1ff8fb1329dae5fb9b9dcd234243899d7a464ceb374e14a05ead27b7c
language: ruby
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - if [ "$ORM_TYPE" = "ACTIVE_RECORD" ]; then bundle exec rake test/active_record; fi
  - if [ "$ORM_TYPE" = "MONGOID" ]; then bundle exec rake test/mongoid; fi
matrix:
  include:
    - rvm: 2.2
      gemfile: gemfiles/active_record_32.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.2
      gemfile: gemfiles/active_record_42.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.2
      gemfile: gemfiles/active_record_50.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.2
      gemfile: gemfiles/active_record_51.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.2
      gemfile: gemfiles/active_record_52.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.2
      gemfile: gemfiles/mongoid_54.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
    - rvm: 2.2
      gemfile: gemfiles/mongoid_64.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
    - rvm: 2.2
      gemfile: gemfiles/mongoid_70.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
    - rvm: 2.3
      gemfile: gemfiles/active_record_32.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.3
      gemfile: gemfiles/active_record_42.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.3
      gemfile: gemfiles/active_record_50.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.3
      gemfile: gemfiles/active_record_51.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.3
      gemfile: gemfiles/active_record_52.gemfile
      env: ORM_TYPE=ACTIVE_RECORD
    - rvm: 2.3
      gemfile: gemfiles/mongoid_54.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
    - rvm: 2.3
      gemfile: gemfiles/mongoid_64.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
    - rvm: 2.3
      gemfile: gemfiles/mongoid_70.gemfile
      env: ORM_TYPE=MONGOID
      services:
        - mongodb
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
