sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=db72eba1ff8fb1329dae5fb9b9dcd234243899d7a464ceb374e14a05ead27b7c
language: ruby
rvm:
  - 2.2
  - 2.3
services:
  - mongodb
gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_52.gemfile
  - gemfiles/mongoid_31.gemfile
  - gemfiles/mongoid_54.gemfile
  - gemfiles/mongoid_64.gemfile
  - gemfiles/mongoid_70.gemfile
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
